const constants = {
  ADD_EVEN: "ADD_EVEN",
  ADD_ODD: "ADD_ODD",
  ADD_ALL: "ADD_ALL",
  SET_FEEDBACK_ODD: "SET_FEEDBACK_ODD",
  SET_FEEDBACK_EVEN: "SET_FEEDBACK_EVEN",
  REMOVE_FEEDBACK: "REMOVE_FEEDBACK",
  REQUEST_API_DATA: "REQUEST_API_DATA",
  RECEIVE_API_DATA: "RECEIVE_API_DATA",
  RESET_NUMBERS: "RESET_NUMBERS",
};

export default constants;
